site_name: Docs | Bagne Tyron-Jean
site_url: https://tyron-docs.readthedocs.io/
use_directory_urls: false
theme:
  name: readthedocs
  highlightjs: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
#nav:
#    - Home: 'index.md' 
#    - SIO:
#      - pFsense:
#        - Introduction: '/sio/pfsense/index'
#      - Nextcloud:
#        - Introduction: '/sio/nextcloud/introduction'
#        - Installation: '/sio/nextcloud/installation'
#      - GLPI:
#        - Introduction: '/sio/glpi/index'
       
#docs_dir: 'docs'
