site_name: Docs | Bagne Tyron-Jean
site_url: https://tyron-docs.readthedocs.io/fr/latest/
use_directory_urls: false
docs_dir: 'docs'

theme:
  name: readthedocs
  highlightjs: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

nav:
    - Home: 'index.md' 
    - SIO:
      - pFsense: '/sio/pfsense/index.md'
      - Nextcloud: '/sio/nextcloud/index.md'
#        - Introduction: 'docs/sio/nextcloud/introduction'
#        - Installation: 'docs/sio/nextcloud/installation'
#      - GLPI:
#        - Introduction: 'docs/sio/glpi/index'
       

